services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8081/api/v1
    container_name: loyalty-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
